CRM_BTM/CRM_BTM/Models/INTERACT.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_BTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERACT
    {
        public long ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public long ACCOUNT_ID { get; set; }
        public long INTERACT_TYPE_ID { get; set; }
        public long INTERACT_DIRECTION_ID { get; set; }
        public long INTERACT_MEDIUM_ID { get; set; }
        public long USER_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> TASKS_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CRM_USER CRM_USER { get; set; }
        public virtual INTERACT_DIRECTION INTERACT_DIRECTION { get; set; }
        public virtual INTERACT_MEDIUM INTERACT_MEDIUM { get; set; }
        public virtual INTERACT_TYPE INTERACT_TYPE { get; set; }
        public virtual TASKS TASKS { get; set; }
    }
}

CRM_BTM/CRM_BTM/Models/INTERACT_TYPE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_BTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERACT_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INTERACT_TYPE()
        {
            this.INTERACT = new HashSet<INTERACT>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERACT> INTERACT { get; set; }
    }
}

CRM_BTM/CRM_BTM/Controllers/InteractController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using CRM_BTM.Models;
using CRM_BTM.Models.ViewModels;
using CustomAuth.Authorization;
using PagedList;


namespace CRM_BTM.Controllers
{   [Authorize]
    public class InteractController : Controller
    {
        private CRMConnection db = new CRMConnection();

        // GET: Interact
        [AuthAuthorize(Roles = "super_admin", Claims = "interact_index")]
        public ActionResult Index(string sortOrder, string currentFilter, int? page)
        {
            ViewBag.Messages = ViewMessage.handleTempData(TempData);
            ViewBag.CurrentSort = sortOrder;

            var model = new InteractModel();

            if ((InteractModel)TempData["InteractSrh"] != null)
            {
                model = (InteractModel)TempData["InteractSrh"];
            }
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            
            model.InteractInfos = db.INTERACT_INFO_V
                                 .Where( a=>
                                    !(model.PeselNip == null & model.ClientFName == null & model.ClientId == null & model.TaskId == null & model.dateFrom == null)
                                     & (a.INTERACT_DIRECTION_ID==model.InteractDirectionId | model.InteractDirectionId==0)
                                     & (a.INTERACT_MEDIUM_ID==model.InteractMediumId | model.InteractMediumId==0)
                                     & (a.INTERACT_TYPE_ID==model.InteractTypeId | model.InteractTypeId==0)
                                     & (a.INTERACT_DATE>=(model.dateFrom == null ? a.INTERACT_DATE : model.dateFrom) )
                                     & (a.INTERACT_DATE<= (model.dateTo == null ? a.INTERACT_DATE : model.dateTo) )
                                     & (a.CLIENT_ID== (model.ClientId == null ? 0 : model.ClientId) | model.ClientId==null)
                                     & (a.CUSTOMER_FULL_NAME.Contains(model.ClientFName) | model.ClientFName == null)
                                     & (a.CLIENT_PESEL==model.PeselNip | a.CLIENT_NIP==model.PeselNip | model.PeselNip == null)
                                     & (a.TASKS_ID==model.TaskId | model.TaskId==null))
                                 .ToList()
                                 .OrderBy(x => x.INTERACT_DATE)
                                 .ThenBy(x => x.INTERACT_ID)
                                 .ToPagedList(pageNumber, pageSize);
            
            model.InteractDirections = db.INTERACT_DIRECTION.ToList();
            model.InteractTypes = db.INTERACT_TYPE.ToList();
            model.InteractMediums = db.INTERACT_MEDIUM.ToList();

            TempData["InteractSrh"] = new InteractModel();
            TempData["InteractSrh"] = model;

            if (model.dateFrom == null) model.dateFrom = DateTime.Today.AddDays(-7);
            if (model.dateTo == null) model.dateTo = DateTime.Today.AddDays(1);

            return View(model);
        }


        [HttpPost]
        [AuthAuthorize(Roles = "super_admin", Claims = "interact_index")]
        public ActionResult Index(InteractModel model)
        {
            TempData["InteractSrh"] = new InteractModel();
            Debug.WriteLine("CLEAR_FORM " + model.clearForm);
            if (model.clearForm)
            {
                model = new InteractModel();
            }
            else
            {
                TimeSpan diff = (model.dateTo - model.dateFrom) == null ? new TimeSpan() : (TimeSpan)(model.dateTo - model.dateFrom);
                Debug.WriteLine("diff " + diff.Days);
                Debug.WriteLine("add " + (model.dateFrom == null ? new DateTime() : ((DateTime)model.dateFrom).AddDays(7)));

                if (model.PeselNip == null & model.ClientFName == null & model.ClientId == null & model.TaskId == null)
                {
                    if (model.dateFrom == null | model.dateTo == null)
                    {
                        ViewMessage.addMessage(TempData, "Can't query unlimited date range without specifying any of Clients attributes or Task ID. Date range set to last 7 days.", ViewMessage.Types.Warning);
                        model.dateTo = DateTime.Now;
                        model.dateFrom = DateTime.Today.AddDays(-7);
                    }
                    else
                    {
                        if (diff.Days > 14)
                        {
                            model.dateTo = ((DateTime)model.dateFrom).AddDays(14);

                            ViewMessage.addMessage(TempData, "Can't query more than 14 days long date range without specifying any of Clients attributes or Task ID. Date range set as " + model.dateFrom + " - " + model.dateTo, ViewMessage.Types.Warning);

                        }

                    }

                }

                TempData["InteractSrh"] = model;
            }
            
            return RedirectToAction("Index");
            
        }


        // GET: Interact/Details/5
        [AuthAuthorize(Roles = "super_admin", Claims = "interact_details")]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            INTERACT iNTERACT = db.INTERACT.Find(id);
            if (iNTERACT == null)
            {
                return HttpNotFound();
            }
            return View(iNTERACT);
        }

        // GET: Create/5
        [AuthAuthorize(Roles = "super_admin", Claims = "interact_create")]
        public ActionResult Create(long? id)
        {
            if (id == null)
            {
                ViewMessage.addMessage(TempData, "No account provided", ViewMessage.Types.Error);
                return RedirectToAction("Index");
            }
            var Account = db.ACCOUNT.Find(id);
            if (Account == null)
            {
                ViewMessage.addMessage(TempData, "Account not found", ViewMessage.Types.Error);
                return RedirectToAction("Index");
            }
            var Interact = new INTERACT() { ACCOUNT_ID = (long)id };

            ViewBag.INTERACT_TYPE_ID = new SelectList(db.INTERACT_TYPE, "ID", "NAME");
            ViewBag.INTERACT_DIRECTION_ID = new SelectList(db.INTERACT_DIRECTION, "ID", "NAME");
            ViewBag.INTERACT_MEDIUM_ID = new SelectList(db.INTERACT_MEDIUM, "ID", "NAME");
            var SLItems = db.TASKS.Where(x => x.ACCOUNT_ID == id).ToList().Select(x => new SelectListItem() {
                Text = (new StringBuilder()).Append("(").Append(x.ID).Append(") ").Append(x.TASK_TYPE.NAME).Append(", ").Append(x.TASK_SUBTYPE.NAME).ToString(),
                Value = x.ID.ToString()
            });

            ViewBag.TASKS_ID = new SelectList(SLItems, "Value", "Text");

            return View(Interact);
        }


        // POST: Create/5
        [ValidateAntiForgeryToken]
        [HttpPost]
        [AuthAuthorize(Roles = "super_admin", Claims = "interact_create")]
        public ActionResult Create(INTERACT Inter)
        {
            if (ModelState.IsValid)
            {
                Inter.USER_ID = CRM_USER.getFromIdentity(db, User.Identity).ID;
                Inter.CREATION_DATE = DateTime.Now;
                db.INTERACT.Add(Inter);
                db.SaveChanges();
                ViewMessage.addMessage(TempData, "Interaction added", ViewMessage.Types.Success);
            } else
            {
                ViewMessage.addMessage(TempData, "Invalid data state", ViewMessage.Types.Error);
                return RedirectToAction("Index");
            }
            var ClientID = db.ACCOUNT.Find(Inter.ACCOUNT_ID).CLIENT_ID;
            return RedirectToAction("Details", "Client", new { id = ClientID });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CRM_BTM/CRM_BTM/Views/Interact/Create.cshtml
@model CRM_BTM.Models.INTERACT
@{
    ViewBag.Title = "New interaction";
}

<hr />
<div>
    @Html.ActionLink("Back to list", "Index", null, new { @class = "btn btn-secondary" })
</div>
<hr />

@using (Html.BeginForm("Create", "Interact", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ACCOUNT_ID)

    <div class="form-group col-12">
        <div class="row">
            @Html.LabelFor(model => model.INTERACT_TYPE_ID, "Type", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("INTERACT_TYPE_ID", null, null, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="form-group col-12">
        <div class="row">
            @Html.LabelFor(model => model.INTERACT_DIRECTION_ID, "Direction", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("INTERACT_DIRECTION_ID", null, null, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="form-group col-12">
        <div class="row">
            @Html.LabelFor(model => model.INTERACT_MEDIUM_ID, "Medium", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("INTERACT_MEDIUM_ID", null, null, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="form-group col-12">
        <div class="row">
            @Html.LabelFor(model => model.TASKS_ID, "Related task", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("TASKS_ID", null, string.Empty, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="form-group col-12">
        <div class="row">
            @Html.LabelFor(model => model.DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.DESCRIPTION, new { @class = "form-control" })
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Back to list", "Index", null, new { @class = "btn btn-secondary" })
    </div>

}

CRM_BTM/CRM_BTM/Views/Interact/Index.cshtml
@model CRM_BTM.Models.InteractModel
@using PagedList.Mvc;

@{
    ViewBag.Title = "Interactions";
}

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<!-- Bootstrap Date-Picker Plugin -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
<link href="~/Content/bootstrap-select.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/bootstrap-select.js"></script>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.clearForm)
    <div id="search" class="card">
        <h6 class="card-header">Search</h6>
        <div class="card-body">
            <div class="row">
                <div class="form-group col-12">
                    <div class="row">
                        @Html.LabelFor(model => model.InteractInfos.FirstOrDefault().INTERACT_DIRECTION, new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            <div class="border-fix d-inline-block">
                                <select name="InteractDirectionId" id="InteractDirectionId" class="selectpicker" data-live-search="true">
                                    <option @{ if (0 == Model.InteractDirectionId) { <text> selected </text>  } } value=0>
                                        -- select --
                                    </option>
                                    @foreach (var item in Model.InteractDirections.OrderBy(x => x.NAME))
                                    {
                                        <option @{ if (item.ID == Model.InteractDirectionId) { <text> selected </text>  } }
                                                value=@item.ID>
                                            @item.NAME
                                        </option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-12">
                    <div class="row">
                        @Html.LabelFor(model => model.InteractInfos.FirstOrDefault().INTERACT_MEDIUM, new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            <div class="border-fix d-inline-block">
                                <select name="InteractMediumId" id="InteractMediumId" class="selectpicker" data-live-search="true">
                                    <option @{ if (0 == Model.InteractMediumId) { <text> selected </text>  } } value=0>
                                        -- select --
                                    </option>
                                    @foreach (var item in Model.InteractMediums.OrderBy(x => x.NAME))
                                    {
                                        <option @{ if (item.ID == Model.InteractMediumId) { <text> selected </text>  } }
                                                value=@item.ID>
                                            @item.NAME
                                        </option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-12">
                    <div class="row">
                        @Html.LabelFor(model => model.InteractInfos.FirstOrDefault().INTERACT_TYPE, new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            <div class="border-fix d-inline-block">
                                <select name="InteractTypeId" id="InteractTypeId" class="selectpicker" data-live-search="true">
                                    <option @{ if (0 == Model.InteractTypeId) { <text> selected </text>  } } value=0>
                                        -- select --
                                    </option>
                                    @foreach (var item in Model.InteractTypes.OrderBy(x => x.NAME))
                                    {
                                        <option @{ if (item.ID == Model.InteractTypeId) { <text> selected </text>  } }
                                                value=@item.ID>
                                            @item.NAME
                                        </option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-12">
                    <div class="row">
                        @Html.LabelFor(model => model.InteractInfos.FirstOrDefault().INTERACT_DATE, new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            <div class="input-daterange input-group" id="datepicker">
                                @Html.EditorFor(model => model.dateFrom, new { htmlAttributes = new { @class = "input-sm form-control", @type = "text", @name = "start" } })
                                <span class="input-group-addon">&nbsp;to&nbsp;</span>
                                @Html.EditorFor(model => model.dateTo, new { htmlAttributes = new { @class = "input-sm form-control", @type = "text", @name = "end" } })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-12">
                    <div class="row">
                        @Html.LabelFor(model => model.InteractInfos.FirstOrDefault().CLIENT_ID, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.ClientId, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                            @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group col-12">
                    <div class="row">
                        @Html.LabelFor(model => model.InteractInfos.FirstOrDefault().CUSTOMER_FULL_NAME, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.ClientFName, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                        </div>
                    </div>
                </div>
                <div class="form-group col-12">
                    <div class="row">
                        <label class="control-label col-md-3">
                            @Html.DisplayNameFor(model => model.InteractInfos.FirstOrDefault().CLIENT_PESEL) / @Html.DisplayNameFor(model => model.InteractInfos.FirstOrDefault().CLIENT_NIP)
                        </label>
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.PeselNip, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                        </div>
                    </div>
                </div>
                <div class="form-group col-12">
                    <div class="row">
                        @Html.LabelFor(model => model.InteractInfos.FirstOrDefault().TASKS_ID, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.TaskId, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                        </div>
                    </div>
                </div>

            </div>

            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
                <input type="button" value="Reset" id="CLR" class="btn btn-danger" />
            </div>

        </div>
    </div>


}

<div class="mt-4 col-12">
    <p>Page @(Model.InteractInfos.PageCount < Model.InteractInfos.PageNumber ? 0 : Model.InteractInfos.PageNumber) of @Model.InteractInfos.PageCount</p>
    @Html.PagedListPager(Model.InteractInfos, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

    <table class="table table-sm table-striped table-hover table-bordered small mw-100 overflow-auto d-sm-table d-block">
        <tr>
            <th>@Html.DisplayNameFor(model => model.InteractInfos.First().INTERACT_ID)</th>
            <th>@Html.DisplayNameFor(model => model.InteractInfos.First().INTERACT_DATE)</th>
            <th>@Html.DisplayNameFor(model => model.InteractInfos.First().CLIENT_ID)</th>
            <th class="xl-only">@Html.DisplayNameFor(model => model.InteractInfos.First().CUSTOMER_FULL_NAME)</th>
            <th>@Html.DisplayNameFor(model => model.InteractInfos.First().INTERACT_DIRECTION)</th>
            <th>@Html.DisplayNameFor(model => model.InteractInfos.First().INTERACT_MEDIUM)</th>
            <th>@Html.DisplayNameFor(model => model.InteractInfos.First().INTERACT_TYPE)</th>
            <th class="xl-only">@Html.DisplayNameFor(model => model.InteractInfos.First().DESCRIPTION)</th>
            <th class="xl-only">@Html.DisplayNameFor(model => model.InteractInfos.First().TASKS_ID)</th>
        </tr>

        @if (Model.InteractInfos.Count != 0)
        {
            foreach (var item in Model.InteractInfos)
            {
                <tr>
                    <td>@Html.DisplayFor(model => item.INTERACT_ID)</td>
                    <td>@Html.DisplayFor(model => item.INTERACT_DATE)</td>
                    <td>@Html.DisplayFor(model => item.CLIENT_ID)</td>
                    <td class="xl-only">@Html.DisplayFor(model => item.CUSTOMER_FULL_NAME)</td>
                    <td>@Html.DisplayFor(model => item.INTERACT_DIRECTION)</td>
                    <td>@Html.DisplayFor(model => item.INTERACT_MEDIUM)</td>
                    <td>@Html.DisplayFor(model => item.INTERACT_TYPE)</td>
                    <td class="xl-only" style="word-wrap: break-word; width: 160px;">@Html.DisplayFor(model => item.DESCRIPTION)</td>
                    <td class="xl-only">
                        @if (item.TASKS_ID != null)
                        {
                            @Html.ActionLink(item.TASKS_ID.ToString(), "details", "tasks", new { id = item.TASKS_ID }, null)
                        }
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="9">To see interactions, use search box above.</td>
            </tr>
        }

    </table>

    <p>Page @(Model.InteractInfos.PageCount < Model.InteractInfos.PageNumber ? 0 : Model.InteractInfos.PageNumber) of @Model.InteractInfos.PageCount</p>
    @Html.PagedListPager(Model.InteractInfos, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

</div>

@section Scripts {

    <script>
        $(document).ready(function () {
            $('.input-daterange').datepicker({
                autoclose: true,
                format: "yyyy-mm-dd"
            });
        })

        $(function () {
            $("#CLR").click(function () {

                $("#clearForm").val(true)

                console.log($("#clearForm").val())
                $("form").submit();


            });
        });

    </script>
}