CRM_BTM/CRM_BTM/Controllers/TasksConfigController.cs
using CRM_BTM.Models;
using CRM_BTM.Models.ViewModels;
using CustomAuth.Authorization;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CRM_BTM.Controllers
{   [Authorize]
    public class TasksConfigController : Controller
    {
        private CRMConnection db = new CRMConnection();

        // GET: TaskConfig
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_index")]
        public ActionResult Index()
        {
            ViewData["displayFull"] = false;
            ViewBag.Messages = ViewMessage.handleTempData(TempData);
            var model = new TasksConfigIndexViewModel() {
                Statuses = db.TASK_STATUS.ToList(),
                Types = db.TASK_TYPE.ToList(),
                Subtypes = db.TASK_SUBTYPE.ToList(),
                Parameters = db.TASK_PARAM_DEFINITION.ToList()
            };
            return View(model);
        }

        // GET: TaskConfig/StatusEdit/5
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_edit")]
        public ActionResult StatusEdit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            TASK_STATUS sts = db.TASK_STATUS.Find(id);
            ACTIVITY_LOG.PrepareForDisplay(ViewBag, sts);
            if (sts == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            return View(sts);
        }

        // POST: TaskConfig/StatusEdit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_edit")]
        public ActionResult StatusEdit(TASK_STATUS sts)
        {
            if (ModelState.IsValid)
            {
                db.TASK_STATUS.Attach(sts);
                var checkUnique = db.TASK_STATUS.Where(x => x.NAME.Equals(sts.NAME)).Where(x => x.ID != sts.ID).Any();
                if (checkUnique)
                {
                    ViewMessage.addMessage(TempData, "Name must be unique.", ViewMessage.Types.Error);
                    return RedirectToAction("Index");
                }
                db.Entry(sts).State = EntityState.Modified;
                db.SaveChangesLog(HttpContext.User.Identity.Name);
                ViewMessage.addMessage(TempData, "Status altered.", ViewMessage.Types.Success);
                return RedirectToAction("StatusList");
            }
            else
            {
                ViewMessage.addMessage(TempData, "Invalid data state.", ViewMessage.Types.Error);
                return RedirectToAction("StatusList");
            }
        }

        // GET: TaskConfig/StatusAdd
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_add")]
        public ActionResult StatusAdd()
        {
            return View();
        }

        // POST: TaskConfig/StatusAdd
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_add")]
        public ActionResult StatusAdd(TASK_STATUS newSts)
        {
            if (ModelState.IsValid)
            {
                var checkUnique = db.TASK_STATUS.Where(x => x.NAME.Equals(newSts.NAME)).Any();
                if (checkUnique)
                {
                    ViewMessage.addMessage(TempData, "Name must be unique.", ViewMessage.Types.Error);
                    return RedirectToAction("Index");
                }
                db.TASK_STATUS.Add(newSts);
                db.SaveChangesLog(HttpContext.User.Identity.Name);
                ViewMessage.addMessage(TempData, "Status created.", ViewMessage.Types.Success);
                return RedirectToAction("StatusList");
            }
            else
            {
                ViewMessage.addMessage(TempData, "Invalid data state.", ViewMessage.Types.Error);
                return RedirectToAction("StatusList");
            }
        }

        // GET: TaskConfig/TypeEdit/5
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_edit")]
        public ActionResult TypeEdit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            TASK_TYPE taty = db.TASK_TYPE.Find(id);
            ACTIVITY_LOG.PrepareForDisplay(ViewBag, taty);
            if (taty == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            return View(taty);
        }

        // POST: TaskConfig/TypeEdit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_edit")]
        public ActionResult TypeEdit(TASK_TYPE taty)
        {
            if (ModelState.IsValid)
            {
                db.TASK_TYPE.Attach(taty);
                var checkUnique = db.TASK_TYPE.Where(x => x.NAME.Equals(taty.NAME)).Where(x => x.ID != taty.ID).Any();
                if (checkUnique)
                {
                    ViewMessage.addMessage(TempData, "Name must be unique.", ViewMessage.Types.Error);
                    return RedirectToAction("Index");
                }
                db.Entry(taty).State = EntityState.Modified;
                db.SaveChangesLog(HttpContext.User.Identity.Name);
                ViewMessage.addMessage(TempData, "Type altered.", ViewMessage.Types.Success);
                return RedirectToAction("TypeList");
            }
            else
            {
                ViewMessage.addMessage(TempData, "Invalid data state.", ViewMessage.Types.Error);
                return RedirectToAction("TypeList");
            }
        }

        // GET: TaskConfig/TypeAdd
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_add")]
        public ActionResult TypeAdd()
        {
            return View();
        }

        // POST: TaskConfig/TypeAdd
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_add")]
        public ActionResult TypeAdd(TASK_TYPE newType)
        {
            if (ModelState.IsValid)
            {
                var checkUnique = db.TASK_TYPE.Where(x => x.NAME.Equals(newType.NAME)).Any();
                if (checkUnique)
                {
                    ViewMessage.addMessage(TempData, "Name must be unique.", ViewMessage.Types.Error);
                    return RedirectToAction("Index");
                }
                db.TASK_TYPE.Add(newType);
                db.SaveChangesLog(HttpContext.User.Identity.Name);
                ViewMessage.addMessage(TempData, "Type created.", ViewMessage.Types.Success);
                return RedirectToAction("TypeList");
            }
            else
            {
                ViewMessage.addMessage(TempData, "Invalid data state.", ViewMessage.Types.Error);
                return RedirectToAction("TypeList");
            }
        }

        // GET: TaskConfig/SubtypeEdit/5
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_edit")]
        public ActionResult SubtypeEdit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            TASK_SUBTYPE subt = db.TASK_SUBTYPE.Find(id);
            ACTIVITY_LOG.PrepareForDisplay(ViewBag, subt);
            if (subt == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            return View(subt);
        }

        // POST: TaskConfig/SubtypeEdit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_edit")]
        public ActionResult SubtypeEdit(TASK_SUBTYPE taty)
        {
            if (ModelState.IsValid)
            {
                db.TASK_SUBTYPE.Attach(taty);
                var checkUnique = db.TASK_SUBTYPE.Where(x => x.NAME.Equals(taty.NAME)).Where(x => x.ID != taty.ID).Any();
                if (checkUnique)
                {
                    ViewMessage.addMessage(TempData, "Name must be unique.", ViewMessage.Types.Error);
                    return RedirectToAction("Index");
                }
                db.Entry(taty).State = EntityState.Modified;
                db.SaveChangesLog(HttpContext.User.Identity.Name);
                ViewMessage.addMessage(TempData, "Subtype altered.", ViewMessage.Types.Success);
                return RedirectToAction("SubtypeList");
            }
            else
            {
                ViewMessage.addMessage(TempData, "Invalid data state.", ViewMessage.Types.Error);
                return RedirectToAction("SubtypeList");
            }
        }

        // GET: TaskConfig/SubtypeAdd
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_add")]
        public ActionResult SubtypeAdd()
        {
            return View();
        }

        // POST: TaskConfig/SubtypeAdd
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthAuthorize(Roles = "super_admin", Claims = "tasksconfig_add")]
        public ActionResult SubtypeAdd(TASK_SUBTYPE newSubtype)
        {
            if (ModelState.IsValid)
            {
                var checkUnique = db.TASK_SUBTYPE.Where(x => x.NAME.Equals(newSubtype.NAME)).Any();
                if (checkUnique)
                {
                    ViewMessage.addMessage(TempData, "Name must be unique.", ViewMessage.Types.Error);
                    return RedirectToAction("Index");
                }
                db.TASK_SUBTYPE.Add(newSubtype);
                db.SaveChangesLog(HttpContext.User.Identity.Name);
                ViewMessage.addMessage(TempData, "Subtype created.", ViewMessage.Types.Success);
                return RedirectToAction("SubtypeList");
            }
            else
            {
                ViewMessage.addMessage(TempData, "Invalid data state.", ViewMessage.Types.Error);

CRM_BTM/CRM_BTM/Views/TasksConfig/Index.cshtml
@model CRM_BTM.Models.ViewModels.TasksConfigIndexViewModel
@{
    ViewBag.Title = "Tasks dashboard";
}

<div class="row">
    <div class="card-wrapper col-12 col-xl-4 mb-4">
        <div id="statuses" class="card bg-light">
            <h6 class="card-header ">
                <a href="@Url.Action("StatusList", "TasksConfig")"><img alt="List" src="@Url.Content("~/Content/Images/link-icon.png")" /></a>
                Available statuses
            </h6>
            <div class="card-body overflow-auto small" style="max-height: 500px;">
                @Html.Partial("PartialViews/StatusList", Model.Statuses.OrderBy(s => s.ID), ViewData)
            </div>
        </div>
    </div>

    <div class="card-wrapper col-12 col-xl-4 mb-4">
        <div id="statuses" class="card bg-light">
            <h6 class="card-header b">
                <a href="@Url.Action("TypeList", "TasksConfig")"><img alt="List" src="@Url.Content("~/Content/Images/link-icon.png")" /></a>
                Available types
            </h6>
            <div class="card-body overflow-auto small" style="max-height: 500px;">
                @Html.Partial("PartialViews/TypeList", Model.Types.OrderBy(s => s.ID), ViewData)
            </div>
        </div>
    </div>

    <div class="card-wrapper col-12 col-xl-4 mb-4">
        <div id="statuses" class="card bg-light">
            <h6 class="card-header b">
                <a href="@Url.Action("SubtypeList", "TasksConfig")"><img alt="List" src="@Url.Content("~/Content/Images/link-icon.png")" /></a>
                Available subtypes
            </h6>
            <div class="card-body overflow-auto small" style="max-height: 500px;">
                @Html.Partial("PartialViews/SubtypeList", Model.Subtypes.OrderBy(s => s.ID), ViewData)
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="card-wrapper col-12">
        <div id="statuses" class="card bg-light">
            <h6 class="card-header b">
                <a href="@Url.Action("ParamList", "TasksConfig")"><img alt="List" src="@Url.Content("~/Content/Images/link-icon.png")" /></a>
                Task parameters
            </h6>
            <div class="card-body overflow-auto small" style="max-height: 800px;">
                @Html.Partial("PartialViews/TaskParameters", Model.Parameters.OrderBy(s => s.ID), ViewData)
            </div>
        </div>
    </div>
</div>

CRM_BTM/CRM_BTM/Views/TasksConfig/ParamAdd.cshtml
@model CRM_BTM.Models.TASK_PARAM_DEFINITION

@{
    ViewBag.Title = "New task parameter";
}

<hr />
<div>
    @Html.ActionLink("Back to list", "ParamList", null, new { @class = "btn btn-secondary" })
</div>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    </div>
    <div class="form-group col-12">
        <div class="row">
            @Html.LabelFor(model => model.PARAM_TYPE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PARAM_TYPE", (SelectList)ViewBag.Types, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PARAM_TYPE, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group col-12">
        <div class="row">
            @Html.LabelFor(model => model.DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DESCRIPTION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group col-12">
        <div class="row">
            @Html.LabelFor(model => model.FULL_DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.FULL_DESCRIPTION, new { @class = "form-control", type = "textarea" })
                @Html.ValidationMessageFor(model => model.FULL_DESCRIPTION, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group col-12">
        <div class="row">
            @Html.LabelFor(model => model.REGEXP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.REGEXP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.REGEXP, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        @Html.ActionLink("Back to list", "ParamList", null, new { @class = "btn btn-secondary" })
    </div>
}

CRM_BTM/CRM_BTM/Views/TasksConfig/ParamEdit.cshtml
@model CRM_BTM.Models.TASK_PARAM_DEFINITION

@{
    ViewBag.Title = "Edit parameter definition";
}

<hr />
<div>
    @Html.ActionLink("Back to list", "ParamList", null, new { @class = "btn btn-secondary" })
    @Html.Partial("_ActivityLogModal")
</div>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-horizontal">
        <div class="form-group col-12">
            <div class="row">
                @Html.LabelFor(model => model.PARAM_TYPE, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("PARAM_TYPE", (SelectList)ViewBag.Types, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PARAM_TYPE, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group col-12">
            <div class="row">
                @Html.LabelFor(model => model.DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DESCRIPTION, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group col-12">
            <div class="row">
                @Html.LabelFor(model => model.FULL_DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.FULL_DESCRIPTION, new { @class = "form-control", type = "textarea" })
                    @Html.ValidationMessageFor(model => model.FULL_DESCRIPTION, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group col-12">
            <div class="row">
                @Html.LabelFor(model => model.REGEXP, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.REGEXP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.REGEXP, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Back to list", "ParamList", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
}

CRM_BTM/CRM_BTM/Views/TasksConfig/ParamEditTypes.cshtml
@model IEnumerable<CRM_BTM.Models.MTM_PARAMDEF_TASKTYPE>

@{
    ViewBag.Title = "Param criteria: " + ViewBag.Parameter.DESCRIPTION;
}

<hr />
<div>
    @Html.ActionLink("Back to list", "ParamList", null, new { @class = "btn btn-secondary" })
</div>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Hidden("paramId", (object)ViewBag.Parameter.ID)

    <div class="form-horizontal">
        @{ int i = 0;}
        <div class="col-md-10" id="valgroup-container">
            @{ ViewData["SectionLabel"] = "template"; }
            @Html.Partial("PartialViews/ParamEditTypesFormSection", new CRM_BTM.Models.MTM_PARAMDEF_TASKTYPE(), ViewData)
            @foreach (CRM_BTM.Models.MTM_PARAMDEF_TASKTYPE val in Model)
            {
                ViewData["SectionLabel"] = i.ToString();
                @Html.Partial("PartialViews/ParamEditTypesFormSection", val, ViewData)
                i++;
            }
        </div>

        <div class="col-10">
            <div class="btn btn-outline-success" id="valgroup-add" onclick="addSection();">Add</div>
        </div>

        <div class="form-group m-3">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Back to list", "ParamList", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
}

@section Scripts {

    <script>
        function addSection() {
            var cont = $("#valgroup-container");
            var childCount = cont.children("div").length;
            if (childCount == 1) {
                var newindex = 0;
                var newSection = $("#valgroup-template").clone();
                newSection.css("display", "");
                changeIndex(newSection, newindex);
                newSection.appendTo("#valgroup-container");
            } else {
                var copiedIndex = childCount - 2;
                var newindex = childCount - 1;
                var newSection = $("#valgroup-" + copiedIndex).clone();
                changeIndex(newSection, newindex);
                newSection.appendTo("#valgroup-container");
            }

        }

        function removeSection(button) {
            var section = $("#" + button.id).parent();
            var cont = $("#valgroup-container");
            var removeIndex = parseInt(button.id.replace("valgroup-remove-", ""));
            var maxIndex = cont.children("div").length - 2;
            section.remove();
            var i = 0;
            for (i = removeIndex + 1; i <= maxIndex; i++) {
                changeIndex(cont.children("#valgroup-" + i), i - 1);
            }

        }

        function changeIndex(section, newIndex) {
            var oldIndex = section.attr("id").replace("valgroup-", "");
            section.attr('id', 'valgroup-' + newIndex);
            section.children("*[name*='.']").each(function (idx) {
                var oldAttr = $(this).attr('name');
                var newAttr = oldAttr.replace(oldIndex, newIndex);
                $(this).attr("name", newAttr);
            });
            section.children("*[name*='.ID']").attr('value', '');
            section.children("*[id|='valgroup-remove']").attr('id', 'valgroup-remove-' + newIndex);
        }
    </script>

}

CRM_BTM/CRM_BTM/Views/TasksConfig/ParamEditValues.cshtml
@model IEnumerable<CRM_BTM.Models.TASK_PARAM_VALUE_LIST>

@{
    ViewBag.Title = "Param value list: " + ViewBag.Parameter.DESCRIPTION;
}

<hr />
<div>
    @Html.ActionLink("Back to list", "ParamList", null, new { @class = "btn btn-secondary" })
</div>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Hidden("paramId", (object)ViewBag.Parameter.ID)

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @{ int i = 0; }

        <div class="col-md-10" id="valgroup-container">
            @{ ViewData["SectionLabel"] = "template"; }
            @Html.Partial("PartialViews/ParamEditValuesFormSection", new CRM_BTM.Models.TASK_PARAM_VALUE_LIST(), ViewData)
            @foreach (CRM_BTM.Models.TASK_PARAM_VALUE_LIST val in Model)
            {
                ViewData["SectionLabel"] = i.ToString();
                @Html.Partial("PartialViews/ParamEditValuesFormSection", val, ViewData)
                i++;
            }
        </div>

        <div class="col-10">
            <div class="btn btn-outline-success" id="valgroup-add" onclick="addSection();">Add</div>
        </div>

        <div class="form-group m-3">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Back to list", "ParamList", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
}
@section Scripts {

    <script>
        function addSection() {
            var cont = $("#valgroup-container");
            var childCount = cont.children("div").length;
            if (childCount == 1) {
                var newindex = 0;
                var newSection = $("#valgroup-template").clone();
                newSection.css("display", "");
                changeIndex(newSection, newindex);
                newSection.children("*[name*='VALUE']").val('');
                newSection.appendTo("#valgroup-container");
            } else {
                var copiedIndex = childCount - 2;
                var newindex = childCount - 1;
                var newSection = $("#valgroup-" + copiedIndex).clone();
                changeIndex(newSection, newindex);
                newSection.children("*[name*='VALUE']").val('');
                newSection.appendTo("#valgroup-container");
            }

        }

        function removeSection(button) {
            var section = $("#" + button.id).parent();
            var cont = $("#valgroup-container");
            var removeIndex = parseInt(button.id.replace("valgroup-remove-", ""));
            var maxIndex = cont.children("div").length - 2;
            console.log("Remove " + section.attr('id'));
            console.log("removeIndex " + removeIndex);
            console.log("maxIndex " + maxIndex);
            section.remove();
            var i = 0;
            for (i = removeIndex + 1; i <= maxIndex; i++) {
                console.log("CHANGING " + i);
                changeIndex(cont.children("#valgroup-" + i), i - 1);
            }

        }

        function changeIndex(section, newIndex) {
            console.log("changeIndex: " + section.attr('id') + " into " + newIndex);
            var oldIndex = section.attr("id").replace("valgroup-", "");
            console.log(oldIndex);
            section.attr('id', 'valgroup-' + newIndex);
            section.children("*[name*='.']").each(function (idx) {
                var oldAttr = $(this).attr('name');
                var newAttr = oldAttr.replace(oldIndex, newIndex);
                $(this).attr("name", newAttr);
            });
            section.children("*[name*='.ID']").attr('value', '');
            section.children("*[id|='valgroup-remove']").attr('id', 'valgroup-remove-' + newIndex);
        }
    </script>

}

CRM_BTM/CRM_BTM/Views/TasksConfig/ParamList.cshtml
@model IEnumerable<CRM_BTM.Models.TASK_PARAM_DEFINITION>

@{
    ViewBag.Title = "Task parameters list";
}

<hr />
<div>
    @Html.ActionLink("Create new", "ParamAdd", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back to dashboard", "Index", null, new { @class = "btn btn-secondary" })
</div>
<hr />

@Html.Partial("PartialViews/TaskParameters", Model, ViewData)

CRM_BTM/CRM_BTM/Views/TasksConfig/StatusAdd.cshtml
@model CRM_BTM.Models.TASK_STATUS

@{
    ViewBag.Title = "New task status";
}

<hr />
<div>
    @Html.ActionLink("Back to list", "StatusList", null, new { @class = "btn btn-secondary" })
</div>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group col-12">
            <div class="row">
                @Html.LabelFor(model => model.NAME, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
            @Html.ActionLink("Back to list", "StatusList", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
}

CRM_BTM/CRM_BTM/Views/TasksConfig/StatusEdit.cshtml
@model CRM_BTM.Models.TASK_STATUS

@{
    ViewBag.Title = "Edit task status";
}

<hr />
<div>
    @Html.ActionLink("Back to list", "StatusList", null, new { @class = "btn btn-secondary" })
    @Html.Partial("_ActivityLogModal")
</div>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group col-12">
            <div class="row">
                @Html.LabelFor(model => model.NAME, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Back to list", "StatusList", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
}

CRM_BTM/CRM_BTM/Views/TasksConfig/StatusList.cshtml
@model IEnumerable<CRM_BTM.Models.TASK_STATUS>

@{
    ViewBag.Title = "Task status list";
}

<hr />
<div>
    @Html.ActionLink("Create new", "StatusAdd", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back to dashboard", "Index", null, new { @class = "btn btn-secondary" })
</div>
<hr />


@Html.Partial("PartialViews/StatusList", Model, ViewData)